// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_CamControlMZ","status":false,"description":"(v.1.7) Allows greater control over where the game camera is focused. View documentation for plugin commands.","parameters":{"useZoom":"true","bZoom":"1"}},
{"name":"TN_SpriteExtender","status":false,"description":"Stretch the torso of the character image at any ratio to raise the body proportion.","parameters":{"bodyRate":"2.00","headRange":"10","exclude_P":"!,Damage","exclude_E":"Nature,Monster,Vehicle","applyWindowClasses":"true"}},
{"name":"EliMZ_Book","status":true,"description":"♦5.4.14♦ Essential plugin for all Eli plugins.","parameters":{"engine":"{\"pixelPerfect\":\"false\",\"styleOverflow\":\"false\",\"--- MZ ONLY ---\":\"\",\"disableEffekseer\":\"false\"}","playtest":"{\"openDevTools\":\"false\",\"nwWindowPos\":\"0, 0\",\"--- MZ ONLY ---\":\"\",\"gameFocus\":\"true\",\"quickRestart\":\"true\"}"}},
{"name":"EliMZ_ButtonCommonEvents","status":true,"description":"♦5.2.3♦ Bind common events to keyboard/gamepad buttons!","parameters":{"presetKeys":"[\"{\\\"key\\\":\\\"q\\\",\\\"id\\\":\\\"2\\\",\\\"isParallel\\\":\\\"false\\\",\\\"overwrite\\\":\\\"false\\\"}\"]","presetKeysGamePad":"[]"}},
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}}
];
